import IMG1 from '../../../assets/me.png';
const data = [
    {
        id:1,
        img:IMG1,
        title:"title",
        github:"github.com/pankaj-kumar63",
        demo:"github.com/pankaj-kumar63"
    },
    {
        id:2,
        img:IMG1,
        title:"title",
        github:"github.com/pankaj-kumar63",
        demo:"github.com/pankaj-kumar63"
    },
    {
        id:3,
        img:IMG1,
        title:"title",
        github:"github.com/pankaj-kumar63",
        demo:"github.com/pankaj-kumar63"
    },
    {
        id:4,
        img:IMG1,
        title:"title",
        github:"github.com/pankaj-kumar63",
        demo:"github.com/pankaj-kumar63"
    },
    {
        id:5,
        img:IMG1,
        title:"title",
        github:"github.com/pankaj-kumar63",
        demo:"github.com/pankaj-kumar63"
    },
    {
        id:6,
        img:IMG1,
        title:"title",
        github:"github.com/pankaj-kumar63",
        demo:"github.com/pankaj-kumar63"
    }
]
export default data;
